######################################################################
# Automatically generated by qmake (2.01a) ? 10? 10 00:30:35 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
